# Generated by Django 4.2 on 2024-02-13 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(max_length=20)),
                ('horario', models.CharField(blank=True, max_length=10, null=True)),
                ('responsable', models.CharField(blank=True, max_length=100, null=True)),
                ('logo', models.ImageField(default='clinicas/default.jpg', upload_to='clinicas/')),
            ],
        ),
    ]
