# Generated by Django 4.2 on 2024-02-29 02:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinicas', '0002_remove_clinica_horario_remove_clinica_responsable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinica',
            name='logo',
            field=models.ImageField(blank=True, default='clinicas/default.jpg', null=True, upload_to='clinicas/'),
        ),
        migrations.RemoveField(
            model_name='clinica',
            name='responsables',
        ),
        migrations.AddField(
            model_name='clinica',
            name='responsables',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
