# Generated by Django 4.2 on 2024-03-21 16:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinicas', '0003_alter_clinica_logo_remove_clinica_responsables_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinica',
            name='jueves',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clinica',
            name='lunes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clinica',
            name='martes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clinica',
            name='miercoles',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clinica',
            name='municipio',
            field=models.CharField(choices=[('AMAXAC DE GUERRERO', 'AMAXAC DE GUERRERO'), ('ACUAMANALA DE MIGUEL HIDALGO', 'ACUAMANALA DE MIGUEL HIDALGO'), ('ALTLANCA', 'ALTLANCA'), ('AMAXAC DE GUERRERO', 'AMAXAC DE GUERRERO'), ('APIZACO', 'APIZACO'), ('ATLANGATEPEC', 'ATLANGATEPEC'), ('BENITO JUÁREZ', 'BENITO JUÁREZ'), ('CALPULALPAN', 'CALPULALPAN'), ('CHIAUTEMPAN', 'CHIAUTEMPAN'), ('CONTLA DE JUAN CUAMATZI', 'CONTLA DE JUAN CUAMATZI'), ('CUAPIAXTLA', 'CUAPIAXTLA'), ('CUAXOMULCO', 'CUAXOMULCO'), ('EL CARMEN TEQUEXQUITLA', 'EL CARMEN TEQUEXQUITLA'), ('EMILIANO ZAPATA', 'EMILIANO ZAPATA'), ('ESPAÑITA', 'ESPAÑITA'), ('HUAMANTLA', 'HUAMANTLA'), ('HUEYOTLIPAN', 'HUEYOTLIPAN'), ('IXTACUIXTLA DE MARIANO MATAMOROS', 'IXTACUIXTLA DE MARIANO MATAMOROS'), ('IXTENCO', 'IXTENCO'), ('LA MAGDALENA TLALTELULCO', 'LA MAGDALENA TLALTELULCO'), ('LÁZARO CÁRDENAS', 'LÁZARO CÁRDENAS'), ('MAZATECOCHCO DE JOSÉ MARÍA MORELOS', 'MAZATECOCHCO DE JOSÉ MARÍA MORELOS'), ('MUÑOZ DE DOMINGO ARENAS', 'MUÑOZ DE DOMINGO ARENAS'), ('NANACAMILPA DE MARIANO ARISTA', 'NANACAMILPA DE MARIANO ARISTA'), ('NATIVITAS', 'NATIVITAS'), ('PANOTLA', 'PANOTLA'), ('PAPALOTLA DE XICOHTÉNCATL', 'PAPALOTLA DE XICOHTÉNCATL'), ('SAN DAMIÁN TEXOLOC', 'SAN DAMIÁN TEXOLOC'), ('SAN FRANCISCO TETLANOHCAN', 'SAN FRANCISCO TETLANOHCAN'), ('SAN JERÓNIMO ZACUALPAN', 'SAN JERÓNIMO ZACUALPAN'), ('SAN JOSÉ TEACALCO', 'SAN JOSÉ TEACALCO'), ('SAN JUAN HUACTZINCO', 'SAN JUAN HUACTZINCO'), ('SAN LORENZO AXOCOMANITLA', 'SAN LORENZO AXOCOMANITLA'), ('SAN LUCAS TECOPILCO', 'SAN LUCAS TECOPILCO'), ('SAN PABLO DEL MONTE', 'SAN PABLO DEL MONTE'), ('SANCTORUM DE LÁZARO CÁRDENAS', 'SANCTORUM DE LÁZARO CÁRDENAS'), ('SANTA ANA NOPALUCAN', 'SANTA ANA NOPALUCAN'), ('SANTA APOLONIA TEACALCO', 'SANTA APOLONIA TEACALCO'), ('SANTA CATARINA AYOMETLA', 'SANTA CATARINA AYOMETLA'), ('SANTA CRUZ QUILEHTLA', 'SANTA CRUZ QUILEHTLA'), ('SANTA CRUZ TLAXCALA', 'SANTA CRUZ TLAXCALA'), ('SANTA ISABEL XILOXOXTLA', 'SANTA ISABEL XILOXOXTLA'), ('TEOLOCHOLCO', 'TEOLOCHOLCO'), ('TEPETITLA DE LARDIZÁBAL', 'TEPETITLA DE LARDIZÁBAL'), ('TETLA DE LA SOLIDARIDAD', 'TETLA DE LA SOLIDARIDAD'), ('TETLATLAHUCA', 'TETLATLAHUCA'), ('TLAXCALA', 'TLAXCALA'), ('TLAXCO', 'TLAXCO'), ('TOTOLAC', 'TOTOLAC'), ('TOCATLÁN', 'TOCATLÁN'), ('TZOMPANTEPEC', 'TZOMPANTEPEC'), ('XALOZTOC', 'XALOZTOC'), ('XALTOCAN', 'XALTOCAN'), ('YAUHQUEMEHCAN', 'YAUHQUEMEHCAN'), ('ZACATELCO', 'ZACATELCO'), ('ZITLALTEPEC DE TRINIDAD SÁNCHEZ SANTOS', 'ZITLALTEPEC DE TRINIDAD SÁNCHEZ SANTOS')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clinica',
            name='sabado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clinica',
            name='viernes',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clinica',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='clinicas/'),
        ),
        migrations.AlterField(
            model_name='clinica',
            name='numero_consultorios',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='clinica',
            name='responsables',
            field=models.ManyToManyField(blank=True, related_name='clinicas_responsables', to=settings.AUTH_USER_MODEL),
        ),
    ]
