# Generated by Django 4.2 on 2024-02-13 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinicas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dentistacalendar',
            name='dentista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dentista_horario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='citasdentalescalendar',
            name='clinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clinica_agenda', to='clinicas.clinica'),
        ),
        migrations.AddField(
            model_name='cita',
            name='clinica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_clinica_cita', to='clinicas.clinica'),
        ),
        migrations.AddField(
            model_name='cita',
            name='dentista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agenda_dentista_citas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cita',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_paciente_citas', to=settings.AUTH_USER_MODEL),
        ),
    ]
