# Generated by Django 4.2 on 2024-02-13 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='estado_cita',
            field=models.CharField(choices=[('Aprobada', 'Aprobada'), ('Rechazada', 'Rechazada'), ('Espera', 'En Espera'), ('Concluida', 'Concluida')], default='Espera', max_length=40),
        ),
    ]
