# Generated by Django 4.2 on 2024-02-13 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='numero',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='No. celular'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='sexo',
            field=models.CharField(blank=True, choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer')], max_length=10, verbose_name='Genero'),
        ),
        migrations.CreateModel(
            name='AsistenteDentista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asistente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistente_dentistas', to=settings.AUTH_USER_MODEL)),
                ('dentista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dentista_asistentes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
