# Generated by Django 4.2 on 2024-03-21 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0004_clinica_jueves_clinica_lunes_clinica_martes_and_more'),
        ('usuarios', '0003_remove_asistente_user_remove_medico_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idiomas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idoma', models.CharField(choices=[('Aleman', 'Aleman'), ('Español', 'Español'), ('Ingles', 'Ingles'), ('Italiano', 'Italiano'), ('Portugues', 'Portugues')], max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='idiomas',
            field=models.CharField(blank=True, choices=[('español', 'Español'), ('inglés', 'Inglés'), ('francés', 'Francés'), ('aleman', 'Alemán')], max_length=255, null=True, verbose_name='Idiomas hablados'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='clinicas',
            field=models.ManyToManyField(related_name='usuarios_asignados', to='clinicas.clinica'),
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dato_especifico_paciente', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula_profesional', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Asistente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dato_especifico_asistente', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dato_especifico_admin', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
